#!/usr/bin/env ruby

def is_perfect?(max, number)
  (1..max).each { |n| return false if number % n != 0 }

  true
end

max = ARGV[0].to_i
number = max

while true
  number += 1

  break if is_perfect?(max, number)
end

puts number
