#!/usr/bin/env ruby

def generate_chain(number, chain)
  return chain.push(number) if number == 1

  chain.push(number)
  if number.even?
    generate_chain(number / 2, chain)
  else
    generate_chain((number * 3) + 1, chain)
  end
end

max_chain_length = -1
max_chain_seed = -1

(1..1000000).each do |n|
  chain_length = generate_chain(n, []).size
  if chain_length > max_chain_length
    max_chain_length = chain_length
    max_chain_seed = n
  end
end

p [max_chain_seed, max_chain_length]
