#!/usr/bin/env ruby

def build_sieve
  sieve = Array.new(ARGV[0].to_i)
  (0..sieve.size-1).each do |n|
    sieve[n] = n
  end
  sieve[0] = nil
  sieve[1] = nil

  (2..sieve.size-1).each do |i|
    index = i * 2

    until index > sieve.size-1 do
      sieve[index] = nil
      index += i
    end
  end

  sieve
end

puts build_sieve.compact.reduce(:+)
